### ISSUE TITLE
Sersic profiles being set to zero flux

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#22] opened 2018-10-25 17:13 UTC
This latest version also is not properly inserting Sersic profiles. In previous versions, our input Sersic sources had significant flux levels. E.g.,
comment: surface brightness 6.917 yielded flux 0.199
Now they mostly yield zero flux:
comment: surface brightness 6.917 yielded flux 0.000

**Comment by york-stsci** [comment] 2018-10-25 21:36
To confirm, which branch is the latest version here, and which branch is the previous version you checked against?

**Comment by benw1** [comment] 2018-10-25 22:31
This is the square_pixel_fix branch.
I'm checking against the bug_fix branch from Dec. 2017:
Metadata-Version: 1.1
Name: stips
Version: 1.0.0rc6

**Comment by york-stsci** [comment] 2018-10-26 21:32
Please provide sample input files and the full logging output of running those input files. In particular, I'm interested in lines starting with "Sersic profile has final size..."

**Comment by benw1** [comment] 2018-10-26 22:14
Please see the attached input and log files. 

[H158_example_input.txt.gz](https://github.com/spacetelescope/STScI-STIPS/files/2521042/H158_example_input.txt.gz)
[H158_example.log.gz](https://github.com/spacetelescope/STScI-STIPS/files/2521043/H158_example.log.gz)

**Comment by york-stsci** [comment] 2018-10-26 22:17
Please also provide a log for your preferred version so that I can compare.

**Comment by benw1** [comment] 2018-10-26 22:42
That older version does not produce much screen output.  I include it below, but it has nothing about the Sersic profiles.  Would you like me to run it again in a different way to get more verbose logs?

Running  H158_example_input.txt 25.6659116539 -37.2100872836
('SEED ', 5056)
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
/local/tmp/anaconda/envs/forSTIPS/lib/python2.7/site-packages/pysynphot/units.py:851: RuntimeWarning: divide by zero encountered in log
  return -1.085736 * N.log(arg) + STZERO
/local/tmp/anaconda/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/astro_image/astro_image.py:394: RuntimeWarning: divide by zero encountered in log10
  vegamags = -2.512 * np.log10(fluxes) - self.zeropoint
/local/tmp/anaconda/envs/forSTIPS/lib/python2.7/site-packages/stips-1.0.0rc6-py2.7.egg/stips/astro_image/astro_image.py:395: RuntimeWarning: divide by zero encountered in log10
  stmags = -2.5 * np.log10(fluxes * self.photflam) - 21.10
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.
(bp__H158) does not have a defined binset in the wavecat table. The waveset of the spectrum will be used instead.

**Comment by york-stsci** [comment] 2018-10-26 22:44
Please run it with a logging level of "info". Having checked the bugfix branch as compared with the square_pixel_fix branch, the addSersicProfile function has not changed between those branches, so at the moment I'm pretty much in the dark as to what might be going on.

**Comment by benw1** [comment] 2018-10-26 23:03
Please let me know how to set the logging level.  Is it a parameter I set in the ObservationModule?

**Comment by york-stsci** [comment] 2018-10-26 23:16
There are two ways to do it. The first is to create a logger and pass it in to the ObservationModule with the keyword "logger" (in that case, you simply set the logging level of the logger you pass in). Alternately, after creating the ObservationModule, you can get to its logger by (pseudo-code):
obs = ObservationModule(parameters)
obs.logger.setLevel(logging.INFO)
assuming that you've imported logging.

**Comment by benw1** [comment] 2018-10-26 23:58
I get an attribute error:
Traceback (most recent call last):
  File "run_stips_74.py", line 16, in <module>
    obs.logger.setLevel(logging.INFO)
AttributeError: 'dict' object has no attribute 'logger'
(forSTIPS) bash-4.2$ 
Code is:
obs = {'instrument': 'WFI', 'filters': ['H158'], 'detectors': 1,'distortion': False, 'oversample': 1,'pupil_mask': '', 'background': 'avg','observations_id': 74, 'exptime': 10000.0,'offsets': [{'offset_id': 3, 'offset_centre': False,'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
obs.logger.setLevel(logging.INFO)

Sorry I'm not well versed in working with loggers...

**Comment by york-stsci** [comment] 2018-10-27 00:00
Note that, in the pseudo-code above, obs is the ObservationModule object that you create, not the dictionary that holds the information about the observation. If you're using the same naming as the example in the README, then it would be "obm.logger.setLevel

**Comment by benw1** [comment] 2018-10-27 22:13
Thanks!  Here's the log.
[old_stips_log.txt.gz](https://github.com/spacetelescope/STScI-STIPS/files/2522251/old_stips_log.txt.gz)

**Comment by york-stsci** [comment] 2018-11-01 13:37
I know that you posted logs from an old version somewhere, but I can't find them on this issue. Can you remember which issue you put them on?

**Comment by benw1** [comment] 2018-11-01 22:13
Working on this...
In the meantime, getting a setup error during setup
byte-compiling build/bdist.linux-x86_64/egg/stips/data/CreatePhoenixGrid.py to CreatePhoenixGrid.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/stips/data/CreatePhoenixGrid.py', 119, 156, '                print("\\t\\t\\t{} of {}: {}: Starting Z = {}, log(g) = {}, Teff = {}, Mabs = {:>4}".format(n+1, total, time.ctime(), Z, logg, teff, mag), end=\'\')\n'))

**Comment by york-stsci** [comment] 2018-11-02 14:16
I'm currently having some trouble figuring out what the issue is with this file. Meanwhile, this file is only used in creating a pre-calculated grid of stellar observations. If you're not planning on doing that locally, you don't need this file.

**Comment by york-stsci** [comment] 2018-11-13 17:47
Do you have an update on whether you are able to compile by removing this file?

**Comment by york-stsci** [comment] 2018-11-13 17:51
At this point, I can't reproduce the error you're getting above. As far as I can tell, the print statement isn't in fact invalid syntax, so it shouldn't be causing any problems. In any case, this should probably be handled as its own issue.

**Comment by benw1** [comment] 2018-11-13 18:22
I do not get the error in python 3, only in python 2.  And the setup still completes, but it does report that syntax error in python 2.

**Comment by york-stsci** [comment] 2018-11-13 18:30
That helps. You hadn't previously mentioned that this was on python 2. Should now be fixed on python 2. And, again, please put any other issues involving installation into a new issue, rather than opening them in the middle of a thread about an issue with sersic profiles.

**Comment by benw1** [comment] 2018-11-16 00:02
Here are the output lists for the old and new STIPS.  They both set *many* service profiles to 0 flux, which does not seem right.  The old STIPS did not produce a log, but I also attach the log from the new STIPS
[sers_test_H_observed_NEWSTIPS_WFIRST-WFI.log](https://github.com/spacetelescope/STScI-STIPS/files/2587466/sers_test_H_observed_NEWSTIPS_WFIRST-WFI.log)
[sers_test_H_observed_OLDSTIPS_WFIRST-WFI.txt](https://github.com/spacetelescope/STScI-STIPS/files/2587467/sers_test_H_observed_OLDSTIPS_WFIRST-WFI.txt)
[sers_test_H_observed_NEWSTIPS_WFIRST-WFI.txt](https://github.com/spacetelescope/STScI-STIPS/files/2587468/sers_test_H_observed_NEWSTIPS_WFIRST-WFI.txt)

**Comment by benw1** [comment] 2018-11-21 18:53
Any word on this issue?  I'd like to be able to add Sersic profiles properly, so that I can generate realistic background galaxy distributions.

**Comment by york-stsci** [comment] 2018-11-21 19:02
As far as I can tell there isn’t any change between the version you preferred and the current version when run with the same sources and random values. In cases where the reported flux is zero, that’s because the supplied parameters result in no pixels with values above the noise floor and, as described in the code, in order to avoid output artifacts the Sersic profile generator automatically sets pixels below the noise floor to zero. I’m happy to incorporate a pull request if you come up with one, but until that point this isn’t an issue that I can devote any more time to at the moment, especially with another open issue on Sersic profiles that will probably result in a rewrite of the generation code in any case.

**Closed by york-stsci** 2018-11-21 19:02 UTC
