### ISSUE TITLE
Oversampled image noise, counts calculation

### ISSUE THREAD

**Issue by rubab1** [spacetelescope/STScI-STIPS#8] opened 2017-10-26 01:06 UTC
The way source counts and noise are converted/added to oversampled images does not appear correct. Examples of four different manifestations of this issue are given below. The simulations were run on the STIPS server with oversample=1 (sim15088962181), oversample=4 (sim150463935141) and oversample=10 (sim150721634948) with the exact same input file.

1. Same sources have *very* different counts on images. For example, in the above referenced simulations, the sources located roughly at coordinate 1991,1947 has peak count 1.2e6 in the 10x10 oversample image, peak count 1.09e5 in the 4x4 oversampled image and is practically absent in the  non-oversampled (1x1) image.

2. Header of nonoversample image says -
Added constant 1.401000/pixel
4x4 image says -
Added constant 0.087563/pixel
10x10 image says -
Added constant 0.014010/pixel

The ratio of the three numbers is 100:16:1  or  10x10:4x4:1x1.

```
$ fitsheader *_*_all1/sim150721634948/*0.fits | tail -n 10
HISTORY Added constant 0.014010/pixel                                           
HISTORY Convolving with file WFI Z087 PSF                                       
HISTORY Adding Poisson Noise with mean -0.0202684178948 and standard deviation 1
HISTORY 45.90071106                                                             
HISTORY Adding Read noise with mean 0.002273 and standard deviation 11.997714   
HISTORY Adding Flatfield residual with mean 1.009788 and standard deviation 0.00
HISTORY 0677                                                                    
HISTORY Adding Dark residual with mean 6.935139 and standard deviation 36.687622
HISTORY Adding Cosmic Ray residual with mean 8.355168 and standard deviation 15.
HISTORY 847800                                                                  
$ fitsheader *_*_all1/sim15088962181/*0.fits | tail -n 10
HISTORY Added constant 1.401000/pixel                                           
HISTORY Convolving with file WFI Z087 PSF                                       
HISTORY Adding Poisson Noise with mean 0.0126674119383 and standard deviation 15
HISTORY 1.82901001                                                              
HISTORY Adding Read noise with mean 0.001589 and standard deviation 11.998897   
HISTORY Adding Flatfield residual with mean 1.009788 and standard deviation 0.00
HISTORY 0677                                                                    
HISTORY Adding Dark residual with mean 6.935139 and standard deviation 36.687622
HISTORY Adding Cosmic Ray residual with mean 8.362853 and standard deviation 15.
HISTORY 854543                                                                  
$ fitsheader *_*_all1/sim150463935141/*0.fits | tail -n 10
HISTORY Added constant 0.087563/pixel                                           
HISTORY Convolving with file WFI Z087 PSF                                       
HISTORY Adding Poisson Noise with mean -0.0112874992192 and standard deviation 1
HISTORY 23.766235352                                                            
HISTORY Adding Read noise with mean -0.000314 and standard deviation 12.000808  
HISTORY Adding Flatfield residual with mean 1.009788 and standard deviation 0.00
HISTORY 0677                                                                    
HISTORY Adding Dark residual with mean 6.935139 and standard deviation 36.687622
HISTORY Adding Cosmic Ray residual with mean 8.356036 and standard deviation 15.
HISTORY 849073 
```

3. STIPS generated 'observed' list has different counts for various sersic profile sources but the same counts for point sources. The point sources have counts exactly matching what was on the input list. The comments column of 'sersic' type sources indicates that surface brightness to count rate conversion is producing different numbers.
```
==> sim15088962181/sim15088962181_Mixed_h15_shell_5Mpc_Z_observed_WFIRST-WFI.txt <==
   148.086682632   965.825812376 sersic 25.5551490099 27.0318278628             0.0 72690.0     comment: surface brightness 0.991 yielded flux 0.000
   3952.17108771   1135.95735006  point 26.4013720657 27.8740084518       0.4564579 72691.0                                                  comment
   1861.64741335   3959.88070844 sersic 31.3375336592 32.7865896555             0.0 72692.0     comment: surface brightness 0.005 yielded flux 0.000
   1137.25690244   2700.22370777 sersic 29.3052738353 30.7640380791             0.0 72693.0     comment: surface brightness 0.032 yielded flux 0.000
    3393.2010395   1621.17494313 sersic 25.4116108506 26.8889753954             0.0 72694.0     comment: surface brightness 1.131 yielded flux 0.000
   3802.00619363   3427.89559554 sersic 29.8693624438 31.3254319969             0.0 72695.0     comment: surface brightness 0.019 yielded flux 0.000
   3297.46424639   2391.77462884 sersic 23.4358507076  24.922653597             nan 72696.0       comment: surface brightness 6.917 yielded flux nan
   1471.59348458   1997.62425897 sersic 27.2576116898 28.7261577593             0.0 72697.0     comment: surface brightness 0.208 yielded flux 0.000
   3546.14340685   3127.47077654 sersic 29.6056785598 31.0630077493             0.0 72698.0     comment: surface brightness 0.024 yielded flux 0.000
   3395.61722597    1205.4344499 sersic 26.1984354579 27.6720412864             0.0 72699.0     comment: surface brightness 0.550 yielded flux 0.000

==> sim150463935141/sim150463935141_Mixed_h15_shell_5Mpc_Z_observed_WFIRST-WFI.txt <==
   148.086682632   965.825812376 sersic 25.5551490099 27.0318278628     2.23866156505 72690.0       comment: surface brightness 0.991 yielded flux 2.239
   3952.17108771   1135.95735006  point 26.4013720657 27.8740084518         0.4564579 72691.0                                                    comment
   1861.64741335   3959.88070844 sersic 31.3375336592 32.7865896555               0.0 72692.0       comment: surface brightness 0.005 yielded flux 0.000
   1137.25690244   2700.22370777 sersic 29.3052738353 30.7640380791               0.0 72693.0       comment: surface brightness 0.032 yielded flux 0.000
    3393.2010395   1621.17494313 sersic 25.4116108506 26.8889753954     1.40424257433 72694.0       comment: surface brightness 1.131 yielded flux 1.404
   3802.00619363   3427.89559554 sersic 29.8693624438 31.3254319969               0.0 72695.0       comment: surface brightness 0.019 yielded flux 0.000
   3297.46424639   2391.77462884 sersic 23.4358507076  24.922653597     4.14992264359 72696.0       comment: surface brightness 6.917 yielded flux 4.150
   1471.59348458   1997.62425897 sersic 27.2576116898 28.7261577593     5.30623399342 72697.0       comment: surface brightness 0.208 yielded flux 5.306
   3546.14340685   3127.47077654 sersic 29.6056785598 31.0630077493               0.0 72698.0       comment: surface brightness 0.024 yielded flux 0.000
   3395.61722597    1205.4344499 sersic 26.1984354579 27.6720412864     5.40324812475 72699.0       comment: surface brightness 0.550 yielded flux 5.403

==> sim150721634948/sim150721634948_Mixed_h15_shell_5Mpc_Z_observed_WFIRST-WFI.txt <==
   148.086682632   965.825812376 sersic 25.5551490099 27.0318278628    11.9370884283 72690.0        comment: surface brightness 0.991 yielded flux 11.937
   3952.17108771   1135.95735006  point 26.4013720657 27.8740084518        0.4564579 72691.0                                                      comment
   1861.64741335   3959.88070844 sersic 31.3375336592 32.7865896555              0.0 72692.0         comment: surface brightness 0.005 yielded flux 0.000
   1137.25690244   2700.22370777 sersic 29.3052738353 30.7640380791              0.0 72693.0         comment: surface brightness 0.032 yielded flux 0.000
    3393.2010395   1621.17494313 sersic 25.4116108506 26.8889753954    22.5941950552 72694.0        comment: surface brightness 1.131 yielded flux 22.594
   3802.00619363   3427.89559554 sersic 29.8693624438 31.3254319969              0.0 72695.0         comment: surface brightness 0.019 yielded flux 0.000
   3297.46424639   2391.77462884 sersic 23.4358507076  24.922653597     22.394097392 72696.0        comment: surface brightness 6.917 yielded flux 22.394
   1471.59348458   1997.62425897 sersic 27.2576116898 28.7261577593    34.7754530685 72697.0        comment: surface brightness 0.208 yielded flux 34.775
   3546.14340685   3127.47077654 sersic 29.6056785598 31.0630077493              0.0 72698.0         comment: surface brightness 0.024 yielded flux 0.000
   3395.61722597    1205.4344499 sersic 26.1984354579 27.6720412864    65.0024681652 72699.0        comment: surface brightness 0.550 yielded flux 65.002
```

**Comment by york-stsci** [comment] 2018-01-19 17:29
I just tried a test run with PSF convolution turned off (to check whether what's being run into is that, since the sub-pixel position is different with different oversampling (with a higher oversample yielding a more accurate position), and the PSF is also different with different oversampling (with, again, a higher oversampling yielding a more accurate PSF), what's happening is simply that better-sampled data has slightly different count rates in its output. For this test, I turned all error modes off (since they do, in fact, add a random factor to the resulting image). The code that I used is in the next comment, although note that I haven't yet checked in the version of STIPS that allows you to turn off PSF convolution.

My results are as follows:

- with PSF convolution off (obs_a and obs_b, resulting in sim_0 and sim_1), 11 pixels are different between the two output files (significantly less than the number of sources), with a maximum difference of 0.0078125, and a mean difference of 2.5e-10 across the image. 
- with PSF convolution on (obs_c and obs_d, resulting in sim_2 and sim_3), we see the same issue as initially shown above (that is, for example, at point (2049, 2048) the oversampled image has 5631.24 counts, whilst the non-oversampled image has 3521.17

This suggests to me that at least the vast majority of the issue is the PSF convolution. Just to check if what's happening has something to do with floating point precision when binning pixels with both background and source counts, I tried running the simulations again with background turned off. In that case, the output arrays without PSF convolution are exactly the same, whilst the outputs with PSF convolution are (in the same co-ordinates) 4601.95 and 2518.60, which is essentially the same as the first results with the background count rate subtracted (slightly off from that, likely because the convolution would yield different results).

Code below:

    import matplotlib
    matplotlib.use('Agg')
    
    from stips.scene_module import SceneModule
    from stips.observation_module import ObservationModule
    
    import logging
    import sys
    
    stream_handler = logging.StreamHandler(sys.stderr)
    stream_handler.setFormatter(logging.Formatter('%(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    logger.addHandler(stream_handler)
    
    scm = SceneModule(logger=logger)
    stellar = {'n_stars': 50, 
               'age_low': 1.0e12, 'age_high': 1.0e12, 
               'z_low': -2.0, 'z_high': -2.0,
               'imf': 'salpeter', 'alpha': -2.35,
               'binary_fraction': 0.1,
               'distribution': 'invpow', 'clustered': True,
               'radius': 100.0, 'radius_units': 'pc',
               'distance_low': 20.0, 'distance_high': 20.0,
               'offset_ra': 0.0, 'offset_dec': 0.0}
    stellar_cat_file = scm.CreatePopulation(stellar)
    
    obs_a = {'instrument': 'WFI', 'filter': 'J129', 'detectors': 1,
             'observations_id': 0,
             'distortion': False,
             'oversample': 5,
             'pupil_mask': '',
             'background': 'avg',
             'exptime': 1000,
             'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
    residual = {'dark': False, 'flat': False, 'cosmic': False, 'poisson': False, 'readnoise': False}
    obm = ObservationModule(obs_a, logger=logger, residual=residual)
    obm.nextObservation()
    output_stellar_catalogues_a = obm.addCatalogue(stellar_cat_file)
    psf_file_a = obm.addError(convolve=False)
    fits_file_a, mosaic_file_a, params_a = obm.finalize(mosaic=False)
    
    obs_b = {'instrument': 'WFI', 'filter': 'J129', 'detectors': 1,
             'observations_id': 1,
             'distortion': False,
             'oversample': 1,
             'pupil_mask': '',
             'background': 'avg',
             'exptime': 1000,
             'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
    residual = {'dark': False, 'flat': False, 'cosmic': False, 'poisson': False, 'readnoise': False}
    obm = ObservationModule(obs_b, logger=logger, residual=residual)
    obm.nextObservation()
    output_stellar_catalogues_b = obm.addCatalogue(stellar_cat_file)
    psf_file_b = obm.addError(convolve=False)
    fits_file_b, mosaic_file_b, params_b = obm.finalize(mosaic=False)
    
    obs_c = {'instrument': 'WFI', 'filter': 'J129', 'detectors': 1,
             'observations_id': 2,
             'distortion': False,
             'oversample': 5,
             'pupil_mask': '',
             'background': 'avg',
             'exptime': 1000,
             'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
    residual = {'dark': False, 'flat': False, 'cosmic': False, 'poisson': False, 'readnoise': False}
    obm = ObservationModule(obs_c, logger=logger, residual=residual)
    obm.nextObservation()
    output_stellar_catalogues_a = obm.addCatalogue(stellar_cat_file)
    psf_file_c = obm.addError(convolve=True)
    fits_file_c, mosaic_file_c, params_c = obm.finalize(mosaic=False)
    
    obs_d = {'instrument': 'WFI', 'filter': 'J129', 'detectors': 1,
             'observations_id': 3,
             'distortion': False,
             'oversample': 1,
             'pupil_mask': '',
             'background': 'avg',
             'exptime': 1000,
             'offsets': [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
    residual = {'dark': False, 'flat': False, 'cosmic': False, 'poisson': False, 'readnoise': False}
    obm = ObservationModule(obs_d, logger=logger, residual=residual)
    obm.nextObservation()
    output_stellar_catalogues_d = obm.addCatalogue(stellar_cat_file)
    psf_file_d = obm.addError(convolve=True)
    fits_file_d, mosaic_file_d, params_d = obm.finalize(mosaic=False)

**Comment by york-stsci** [comment] 2018-01-19 17:31
Based on the above, I'm planning to close this issue, since it seems to be a case of STIPS doing exactly what it's supposed to do (i.e. giving different PSF convolution results when oversampled as a result of more accurate source position and more accurate PSF).

**Comment by rubab1** [comment] 2018-01-19 18:52
@york-stsci I agree that from a technical perspective, it seems reasonable to now close this issue. I'd suggest that the documentation is updated to include some details about the differences expected from using different oversampling, to avoid confusion in the longer term.

There are various details that appears to change with oversampling that are not but might need re-visiting. One is varying "zero point offsets" in any given filter with oversampling variations, which we suspect is simply a function of the issues discussed here. For our SIT's primary use-case (point source recovery and flux measurement), we have adequate understanding of this. We will report if any broader issues are identified later.

Thank you & good luck!

**Closed** 2018-01-19 18:56 UTC
Labels: High, bug
